const question = document.getElementById("question");
const choices = Array.from(document.getElementsByClassName("choice-text"));
const progressText = document.getElementById("progressText");
const scoreText = document.getElementById("score");
const progressBarFull = document.getElementById("progressBarFull");

let currentQuestion = {};
let acceptingAnswers = false;
let score = 0;
let questionCounter = 0;
let availableQuestions = [];

let questions = [
  {
    question:
      "What is the main environmental impact of excessive digital data storage?",
    choice1: "Air pollution",
    choice2: "Increased greenhouse gas emissions",
    choice3: "Water contamination",
    choice4: "Soil degradation",
    answer: 2,
  },
  {
    question:
      "What percentage of global greenhouse gas emissions is attributed to data processing and storage?",
    choice1: "0,5%",
    choice2: "1%",
    choice3: "2%",
    choice4: "4%",
    answer: 4,
  },
  {
    question: "What does the term 'digital footprint' primarily refer to?",
    choice1: "The physical traces left by digital devices",
    choice2: "The environmental impact of digital device manufacturing",
    choice3:
      "The data and information generated by an individual’s online activity",
    choice4: "The number of electronic devices a person owns",
    answer: 3,
  },
  {
    question:
      "What is a key long-term benefit of better data management habits?",
    choice1: "Reducing the carbon footprint of data storage",
    choice2: "Making devices heavier and more durable",
    choice3: "Eliminating the need for updates",
    choice4: "Accessing internet services faster worldwide",
    answer: 1,
  },
  {
    question: "What is the main energy source for most data centers?",
    choice1: "Solar",
    choice2: "Wind",
    choice3: "Non-renewable sources like coal and natural gas",
    choice4: "Nuclear power",
    answer: 3,
  },
  {
    question:
      "Which of the following activities contributes to your digital footprint?",
    choice1: "Streaming videos",
    choice2: "Sending emails",
    choice3: "Uploading photos to the cloud",
    choice4: "All of the above",
    answer: 4,
  },
  {
    question:
      "Why should duplicate files be removed from devices or cloud storage?",
    choice1: "They slow down the internet",
    choice2: "They consume unnecessary storage and energy resources",
    choice3: "They increase device battery consumption",
    choice4: "They attract malware",
    answer: 2,
  },
  {
    question: "What is one benefit of digital decluttering?",
    choice1: "Faster internet speeds globally",
    choice2: "Reducing the environmental impact of data storage",
    choice3: "Unlimited storage space",
    choice4: "No need for backups",
    answer: 2,
  },
  {
    question:
      "Which Sustainable Development Goal (SDG) directly relates to digital decluttering?",
    choice1: "SDG 7: Affordable and Clean Energy",
    choice2: "SDG 12: Responsible Consumption and Production",
    choice3: "SDG 16: Peace, Justice, and Strong Institutions",
    choice4: "SDG 4: Quality Education",
    answer: 2,
  },
  {
    question: "What is one strategy to reduce your digital footprint?",
    choice1: "Increase the number of files stored in the cloud",
    choice2: "Use cloud storage more frequently without reviewing files",
    choice3: "Regularly delete unused apps and outdated files",
    choice4: "Avoid organizing files into folders",
    answer: 3,
  },
];

const CORRECT_BONUS = 10;
const MAX_QUESTIONS = 10;

startGame = () => {
  questionCounter = 0;
  score = 0;
  availableQuestions = [...questions];
  getNewQuestion();
};

getNewQuestion = () => {
  if (availableQuestions.length === 0 || questionCounter >= MAX_QUESTIONS) {
    localStorage.setItem("mostRecentScore", score);
    return window.location.assign("end.html");
  }
  questionCounter++;
  progressText.innerText = ` Question ${questionCounter}/${MAX_QUESTIONS}`;

  progressBarFull.style.width = `${
    ((questionCounter - 1) / MAX_QUESTIONS) * 100
  }%`;

  const questionIndex = Math.floor(Math.random() * availableQuestions.length);
  currentQuestion = availableQuestions[questionIndex];
  question.innerText = currentQuestion.question;

  choices.forEach((choice) => {
    const number = choice.dataset["number"];
    choice.innerText = currentQuestion["choice" + number];
  });

  availableQuestions.splice(questionIndex, 1);

  acceptingAnswers = true;
};

choices.forEach((choice) => {
  choice.addEventListener("click", (e) => {
    if (!acceptingAnswers) return;

    acceptingAnswers = false;
    const selectedChoice = e.target;
    const selectedAnswer = selectedChoice.dataset["number"];

    let classToApply = "incorrect";
    if (selectedAnswer == currentQuestion.answer) {
      classToApply = "correct";
    }

    if (classToApply === "correct") {
      incrementScore(CORRECT_BONUS);
    }
    selectedChoice.parentElement.classList.add(classToApply);
    setTimeout(() => {
      selectedChoice.parentElement.classList.remove(classToApply);
      getNewQuestion();
    }, 1000);
  });
});

incrementScore = (num) => {
  score += num;
  scoreText.innerText = score;
};

startGame();
